'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.269
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("White")>  _
        Public Property CanvasColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("CanvasColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("CanvasColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 8.25pt")>  _
        Public Property CanvasFont() As Global.System.Drawing.Font
            Get
                Return CType(Me("CanvasFont"),Global.System.Drawing.Font)
            End Get
            Set
                Me("CanvasFont") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Color1() As Global.System.Drawing.Color
            Get
                Return CType(Me("Color1"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Color1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Color2() As Global.System.Drawing.Color
            Get
                Return CType(Me("Color2"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Color2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Color3() As Global.System.Drawing.Color
            Get
                Return CType(Me("Color3"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Color3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Color4() As Global.System.Drawing.Color
            Get
                Return CType(Me("Color4"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Color4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Color5() As Global.System.Drawing.Color
            Get
                Return CType(Me("Color5"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Color5") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Color6() As Global.System.Drawing.Color
            Get
                Return CType(Me("Color6"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Color6") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Color7() As Global.System.Drawing.Color
            Get
                Return CType(Me("Color7"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Color7") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Color8() As Global.System.Drawing.Color
            Get
                Return CType(Me("Color8"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Color8") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Color9() As Global.System.Drawing.Color
            Get
                Return CType(Me("Color9"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Color9") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Color10() As Global.System.Drawing.Color
            Get
                Return CType(Me("Color10"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Color10") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Color11() As Global.System.Drawing.Color
            Get
                Return CType(Me("Color11"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Color11") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Color12() As Global.System.Drawing.Color
            Get
                Return CType(Me("Color12"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Color12") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Color13() As Global.System.Drawing.Color
            Get
                Return CType(Me("Color13"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Color13") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Color14() As Global.System.Drawing.Color
            Get
                Return CType(Me("Color14"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Color14") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Color15() As Global.System.Drawing.Color
            Get
                Return CType(Me("Color15"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Color15") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("None")>  _
        Public Property VPath() As String
            Get
                Return CType(Me("VPath"),String)
            End Get
            Set
                Me("VPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5")>  _
        Public Property SendDelay() As Integer
            Get
                Return CType(Me("SendDelay"),Integer)
            End Get
            Set
                Me("SendDelay") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property RememberChannel() As Boolean
            Get
                Return CType(Me("RememberChannel"),Boolean)
            End Get
            Set
                Me("RememberChannel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("6")>  _
        Public Property colDefault() As Integer
            Get
                Return CType(Me("colDefault"),Integer)
            End Get
            Set
                Me("colDefault") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property colDialog() As Integer
            Get
                Return CType(Me("colDialog"),Integer)
            End Get
            Set
                Me("colDialog") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public Property colForeign() As Integer
            Get
                Return CType(Me("colForeign"),Integer)
            End Get
            Set
                Me("colForeign") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("14")>  _
        Public Property colTelepathy() As Integer
            Get
                Return CType(Me("colTelepathy"),Integer)
            End Get
            Set
                Me("colTelepathy") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("""")>  _
        Public Property txtDialog() As String
            Get
                Return CType(Me("txtDialog"),String)
            End Get
            Set
                Me("txtDialog") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("*")>  _
        Public Property txtForeign() As String
            Get
                Return CType(Me("txtForeign"),String)
            End Get
            Set
                Me("txtForeign") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("~")>  _
        Public Property txtTelepathy() As String
            Get
                Return CType(Me("txtTelepathy"),String)
            End Get
            Set
                Me("txtTelepathy") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("6")>  _
        Public Property colBegin() As Integer
            Get
                Return CType(Me("colBegin"),Integer)
            End Get
            Set
                Me("colBegin") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("6")>  _
        Public Property colNext() As Integer
            Get
                Return CType(Me("colNext"),Integer)
            End Get
            Set
                Me("colNext") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("6")>  _
        Public Property colContinue() As Integer
            Get
                Return CType(Me("colContinue"),Integer)
            End Get
            Set
                Me("colContinue") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("6")>  _
        Public Property colDone() As Integer
            Get
                Return CType(Me("colDone"),Integer)
            End Get
            Set
                Me("colDone") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property txtBegin() As String
            Get
                Return CType(Me("txtBegin"),String)
            End Get
            Set
                Me("txtBegin") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("--")>  _
        Public Property txtNext() As String
            Get
                Return CType(Me("txtNext"),String)
            End Get
            Set
                Me("txtNext") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("--")>  _
        Public Property txtContinue() As String
            Get
                Return CType(Me("txtContinue"),String)
            End Get
            Set
                Me("txtContinue") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property txtDone() As String
            Get
                Return CType(Me("txtDone"),String)
            End Get
            Set
                Me("txtDone") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property AlwaysTop() As Boolean
            Get
                Return CType(Me("AlwaysTop"),Boolean)
            End Get
            Set
                Me("AlwaysTop") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ClearSend() As Boolean
            Get
                Return CType(Me("ClearSend"),Boolean)
            End Get
            Set
                Me("ClearSend") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property Standalone() As Boolean
            Get
                Return CType(Me("Standalone"),Boolean)
            End Get
            Set
                Me("Standalone") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Color0() As Global.System.Drawing.Color
            Get
                Return CType(Me("Color0"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Color0") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property FirstRun() As Boolean
            Get
                Return CType(Me("FirstRun"),Boolean)
            End Get
            Set
                Me("FirstRun") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property AutoColor() As Boolean
            Get
                Return CType(Me("AutoColor"),Boolean)
            End Get
            Set
                Me("AutoColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property UseBookends() As Boolean
            Get
                Return CType(Me("UseBookends"),Boolean)
            End Get
            Set
                Me("UseBookends") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property CutPreview() As Boolean
            Get
                Return CType(Me("CutPreview"),Boolean)
            End Get
            Set
                Me("CutPreview") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.FatMouth.My.MySettings
            Get
                Return Global.FatMouth.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
